spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cocuschallenge
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/liquibase/master.xml
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379