name: Validate Build and Tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with Maven
      run: mvn test --file pom.xml

    - name: Validate build and tests
      run: |
        if [ ${{ steps.build.outcome }} == 'success' ] && [ ${{ steps.tests.outcome }} == 'success' ]; then
          echo "Build and tests passed!"
        else
          echo "Build or tests failed!"
          exit 1
        fi
